# -*- coding: utf-8 -*-
"""Market_Basket_Optimisation.ipynb"

Automatically generated by Colab.

"""

import pandas as pd
import numpy as np

df = pd.read_csv('Market_Basket_Optimisation.csv')
df.head()

df.info()

"""Гистограммы относительной и
фактической частоты встречаемости для 20 наиболее популярных
товаров
"""

df.stack().value_counts().head(20)

df.stack().value_counts(normalize=True).head(20)

# относительная
df.stack().value_counts(normalize=True).head(20).plot(kind='bar')

# фактическая
df.stack().value_counts().head(20).apply(lambda item: item/df.shape[0]).plot(kind='bar')

"""Применение алгоритма apriori с использованием трёх библиотек
(apriori_python, apyori, efficient_apriori). Подбор гиперпараметров для вывода топ 10 пар
"""

# преобразование датасета в фомат списка транзакций (списка списков)
transactions = []
for i in range(df.shape[0]):
  row = df.iloc[i].dropna().tolist()
  transactions.append(row)

transactions[0]

# замер времени
import time
times = []

# support - frequency, at which items are bought. rulling out items that are not bought frequently
# confidence - how often items occur together
# lift - the accurance of randomness. насколько лучше по сравнению с чистой случайностью

# apriori_python
from apriori_python import apriori

start = time.perf_counter()
t1, rules = apriori(transactions, minSup=0.04, minConf=0.17)
time1 = (time.perf_counter() - start)
times.append(time1)

rules

len(rules)

# apyori
from apyori import apriori

start = time.perf_counter()
rules = apriori(transactions=transactions,
                min_support = 0.04,
                min_confidence = 0.17,
                min_lift = 1.0001)
results = list(rules)
time2 = (time.perf_counter() - start)
times.append(time2)

for result in results:
  for subset in result[2]:
    print(subset[0], subset[1])
    print('support: {0}, conf: {1}, lift: {2}'.format(result[1], subset[2], subset[3]))
    print()

# efficient_apriori

from efficient_apriori import apriori

start = time.perf_counter()
itemsets, rules = apriori(transactions, min_support=0.04, min_confidence=0.17)
time3 = (time.perf_counter()-start)
times.append(time3)

for i in range(len(rules)):
  print(rules[i])

"""Применение алгоритма FP-Growth из библиотеки fpgrowth_py.

https://loginom.ru/blog/fpg
"""

from fpgrowth_py import fpgrowth

start - time.perf_counter()
itemsets, rules = fpgrowth(transactions, minSupRatio=0.04, minConf=0.17)
time4 = (time.perf_counter()-start)
times.append(time4)

for i in range(len(rules)):
  print(rules[i])

"""Сравнение времени выполнения всех алгоритмов на данном датасете

"""

import matplotlib.pyplot as plt

plt.bar(['apriori_python', 'apyori', 'efficient_apriori', 'fpgrowth'], times)